#!/usr/bin/env python3

from collections import Counter

def isAnagram(l, r):
    if Counter(l) == Counter(r):
        return True
    return False

def listAnagrams(c, l):
    res = list(filter(lambda e: isAnagram(c, e), l))
    return res

def main():
    print(listAnagrams('abba', ['aabb', 'abcd', 'bbaa', 'dada']))
    print(listAnagrams('racer', ['crazer', 'carer', 'racar', 'caers', 'racer']))
    print(listAnagrams('laser', ['lazing', 'lazy',  'lacer']))

if __name__ == "__main__":
    main()